phoenixclient/lib/phoenixclient_web/router.ex
defmodule PhoenixclientWeb.Router do
  use PhoenixclientWeb, :router
  alias Routes

  pipeline :auth do #ログイン認証のためのパイプライン
    plug Phoenixclient.Accounts.Pipeline
  end

  pipeline :ensure_auth do  #ログイン済みであるかの判断のためのパイプライン
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json","multipart"]
  end

'''
  scope "/", PhoenixclientWeb do
    pipe_through [:browser, :api, :auth]

    post "/login", LoginController, :login #loginのための情報送信
    post "/add", RelationController, :add #フレンド申請
    delete "/logout", LoginController, :delete
    get "/", PageController, :index

    get "/login", LoginController, :index   #login画面を表示
  end
'''

  scope "/", PhoenixclientWeb do
    pipe_through :api
    get "/", PageController, :index

    get "/search", SearchController, :search#検索
    get "/locsearch", SearchController, :locsearch#検索

    resources "/users", UserController #usersパスへのすべてのリクエストを許可
    get "/userdata", UserController, :get_user # ユーザーのデータ取得

    resources "/locations", LocationController#位置登録

    post "/auth", LoginController, :auth # トークン認証のためのリクエスト
    post "/login", LoginController, :login # loginのための情報送信
    post "/logout", LoginController, :logout
    post "/refresh_token", LoginController, :refresh_token #アクセストークン再発行のルーティング

    post "/relations", RelationController, :add #フレンド追加
    get "/relations", RelationController, :index
    post "/accept", RelationController, :accept
    get "/incoming", RelationController, :incoming
    post "/image", ImageController, :upload# 画像アップロード
  end

  # scope "/", PhoenixclientWeb do
  # pipe_through [:browser, :auth, :ensure_auth]


  # Other scopes may use custom stacks.
  # scope "/api", PhoenixclientWeb do
  #   pipe_through :api
  # end
end

phoenixclient/lib/phoenixclient/accounts/user.ex
defmodule Phoenixclient.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Comeonin.Bcrypt
  schema "users" do
    field :email, :string
    field :name, :string
    field :password, :string

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email, :password])
    |> validate_required([:name, :email, :password])
    |> unique_constraint(:email)
    |> validate_format(:email, ~r/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i)
    |> validate_length(:password, min: 5)
    |> put_pass_hash()
  end

  defp put_pass_hash(%Ecto.Changeset{valid?: true, changes: %{password: password}} = changeset) do
    change(changeset, password: Bcrypt.hashpwsalt(password))
  end
  defp put_pass_hash(changeset), do: changeset
end

phoenixclient/lib/phoenixclient_web/controllers/user_controller.ex
defmodule PhoenixclientWeb.UserController do
  use PhoenixclientWeb, :controller

  alias Phoenixclient.Accounts
  alias Phoenixclient.Accounts.User

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.json", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn,_user) do
    IO.inspect("params=")
    IO.inspect(conn)
    user_params = 
      %{"name" => conn.params["name"],"email" => conn.params["email"],"password" => conn.params["password"]}
      |>IO.inspect
    case Accounts.create_user(user_params) do
      {:ok, user} -> 
        redirect(conn,to: Routes.user_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        send_resp(conn, 502, "Oops, something went wrong!")
    end
  end

  def show(conn, _) do
    user = Accounts.get_user!(conn.params["id"])
    render(conn, "show.json", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end

  def get_user(conn, _) do
    user = Accounts.get_user_from_id(conn.params["id"])
    render(conn, "user.json", user: user)
  end
end

phoenixclient/lib/phoenixclient_web/views/user_view.ex
defmodule PhoenixclientWeb.UserView do
  use PhoenixclientWeb, :view
  alias Phoenixclient.Accounts
  alias PhoenixclientWeb.UserView
  def render("index.json", %{users: users}) do
    %{data: render_many(users, UserView, "user.json")}
  end

  def render("show.json", %{user: user}) do
    %{data: render_one(user, UserView, "user.json")}
  end

  def render("user.json", %{user: user}) do
    %{id: user.id,
      email: user.email,
      name: user.name}
  end
end

phoenixclient/lib/phoenixclient_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

phoenixclient/lib/phoenixclient_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <%= label f, :password %>
  <%= text_input f, :password %>
  <%= error_tag f, :password %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

phoenixclient/lib/phoenixclient_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.password %></td>

      <td>
        <span><%= link "Show", to: Routes.user_path(@conn, :show, user) %></span>
        <span><%= link "Edit", to: Routes.user_path(@conn, :edit, user) %></span>
        <span><%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %></span>
        <%= if Accounts.current_user(@conn) do %>
          <%= if Accounts.current_user(@conn).email != user.email do %>
            <%= form_for @conn, Routes.relation_path(@conn, :add), fn f -> %>

              <%= hidden_input f, :destinationID, value: user.id %>
              <%= submit "Add" %>

            <% end %>
          <% end %>
        <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

phoenixclient/lib/phoenixclient_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

phoenixclient/lib/phoenixclient_web/templates/user/show.html.eex
<h1>Show User</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Password:</strong>
    <%= @user.password %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>