phoenixclient/lib/phoenixclient_web/router.ex
defmodule PhoenixclientWeb.Router do
  use PhoenixclientWeb, :router
  alias Routes

  pipeline :auth do #ログイン認証のためのパイプライン
    plug Phoenixclient.Accounts.Pipeline
  end

  pipeline :ensure_auth do  #ログイン済みであるかの判断のためのパイプライン
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json","multipart"]
  end

'''
  scope "/", PhoenixclientWeb do
    pipe_through [:browser, :api, :auth]

    post "/login", LoginController, :login #loginのための情報送信
    post "/add", RelationController, :add #フレンド申請
    delete "/logout", LoginController, :delete
    get "/", PageController, :index

    get "/login", LoginController, :index   #login画面を表示
  end
'''

  scope "/", PhoenixclientWeb do
    pipe_through :api
    get "/", PageController, :index

    get "/search", SearchController, :search#検索
    get "/locsearch", SearchController, :locsearch#検索

    resources "/users", UserController #usersパスへのすべてのリクエストを許可
    get "/userdata", UserController, :get_user # ユーザーのデータ取得

    resources "/locations", LocationController#位置登録

    post "/auth", LoginController, :auth # トークン認証のためのリクエスト
    post "/login", LoginController, :login # loginのための情報送信
    post "/logout", LoginController, :logout
    post "/refresh_token", LoginController, :refresh_token #アクセストークン再発行のルーティング

    post "/relations", RelationController, :add #フレンド追加
    get "/relations", RelationController, :index
    post "/accept", RelationController, :accept
    get "/incoming", RelationController, :incoming
    post "/image", ImageController, :upload# 画像アップロード
  end

  # scope "/", PhoenixclientWeb do
  # pipe_through [:browser, :auth, :ensure_auth]


  # Other scopes may use custom stacks.
  # scope "/api", PhoenixclientWeb do
  #   pipe_through :api
  # end
end

phoenixclient/lib/phoenixclient/relations.ex
defmodule Phoenixclient.Relations do
  @moduledoc """
  The Relations context.
  """

  import Ecto.Query, warn: false
  alias Phoenixclient.Repo
  alias Phoenixclient.Accounts.User

  alias Phoenixclient.Relations.Relation

  @doc """
  Returns the list of relation.

  ## Examples

      iex> list_relation()
      [%Relation{}, ...]

  """
  def list_relation do
    Repo.all(Relation)
  end

  def get_incoming_users(userid) do
    inc = Relation
          |>where([u], u.destinationID == ^userid)
          |>where([u], not u.status)
          |>Repo.all

    Enum.map(inc, fn r ->
              User
              |> where([u], u.id == ^r.sourceID)
              |> Repo.one()
            end)
  end

  @doc """
  Gets a single relation.

  Raises `Ecto.NoResultsError` if the Relation does not exist.

  ## Examples

      iex> get_relation!(123)
      %Relation{}

      iex> get_relation!(456)
      ** (Ecto.NoResultsError)

  """
  def get_relation!(id), do: Repo.get!(Relation, id)

  @doc """
  Creates a relation.

  ## Examples

      iex> create_relation(%{field: value})
      {:ok, %Relation{}}

      iex> create_relation(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_relation(attrs \\ %{}) do
    val = Map.put(attrs, :status, false)
    %Relation{}
    |> Relation.changeset(val)
    |> Repo.insert()
    |>IO.inspect
    "Sent the friend request!"
  end

  @doc """
  Updates a relation.

  ## Examples

      iex> update_relation(relation, %{field: new_value})
      {:ok, %Relation{}}

      iex> update_relation(relation, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_relation(%Relation{} = relation, attrs) do
    relation
    |> Relation.changeset(attrs)
    |> Repo.update()
  end

  def accept_user(id, destinationUser) do
    from(p in Relation,
        where: p.sourceID == ^destinationUser
        and    p.destinationID == ^id)
    |> Repo.update_all(set: [status: true])
  end
  @doc """
  Deletes a Relation.

  ## Examples

      iex> delete_relation(relation)
      {:ok, %Relation{}}

      iex> delete_relation(relation)
      {:error, %Ecto.Changeset{}}

  """
  def delete_relation(%Relation{} = relation) do
    Repo.delete(relation)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking relation changes.

  ## Examples

      iex> change_relation(relation)
      %Ecto.Changeset{source: %Relation{}}

  """
  def change_relation(%Relation{} = relation) do
    Relation.changeset(relation, %{})
  end

  def check_rel(rel) do
    query =
      from u in Relation,
      where: (u.sourceID == ^rel.sourceID and u.destinationID == ^rel.destinationID)
      or (u.sourceID == ^rel.destinationID and u.destinationID == ^rel.sourceID and u.status == true)
    Repo.one(query)
    |>is_nil
  end

  def searchfriend(id) do
    source_side =
      Task.async(fn ->
      Relation
      |>where([u],u.sourceID == ^id)
      |>where([u], u.status ==true)
      |>Repo.all()
      |>Enum.map(fn(x) -> x.destinationID end)
      end)

    destination_side =
      Relation
      |>where([u],u.destinationID == ^id)
      |>where([u], u.status == true)
      |>Repo.all()
      |>Enum.map(fn(x) -> x.sourceID end)

    Task.await(source_side) ++ destination_side
  end

  def check_duplicate(relation) do
    query =
      from u in Relation,
      where:
        ^relation.sourceID == u.destinationID
        and ^relation.destinationID  == u.sourceID

      rel = Repo.one(query)
    case is_nil(rel) do
      true -> create_relation(relation)
      false -> adjust_duplicate(rel)
    end
  end

  defp adjust_duplicate(relation) do
    accept_user(relation.destinationID,relation.sourceID)
    "Became friend!"
  end
end

phoenixclient/lib/phoenixclient/relations/relation.ex
defmodule Phoenixclient.Relations.Relation do
  use Ecto.Schema
  import Ecto.Changeset

  schema "relation" do
    field :destinationID, :integer
    field :sourceID, :integer
    field :status, :boolean, default: false

    timestamps()
  end

  @doc false
  def changeset(relation, attrs) do
    relation
    |> cast(attrs, [:sourceID, :destinationID, :status])
    |> validate_required([:sourceID, :destinationID, :status])
  end
end

phoenixclient/lib/phoenixclient_web/controllers/relation_controller.ex
defmodule PhoenixclientWeb.RelationController do
  use PhoenixclientWeb, :controller

  alias Phoenixclient.Relations
  alias Phoenixclient.Relations.Relation
  alias Phoenixclient.Accounts

  def index(conn, _params) do
    relation = Relations.list_relation()
    render(conn, "index.json", relation: relation)
  end

  def new(conn, _params) do
    changeset = Relations.change_relation(%Relation{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"relation" => relation_params}) do
    case Relations.create_relation(relation_params) do
      {:ok, relation} ->
        conn
        |> redirect(to: Routes.relation_path(conn, :show, relation))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    relation = Relations.get_relation!(id)
    render(conn, "show.html", relation: relation)
  end

  def edit(conn, %{"id" => id}) do
    relation = Relations.get_relation!(id)
    changeset = Relations.change_relation(relation)
    render(conn, "edit.html", relation: relation, changeset: changeset)
  end

  def update(conn, %{"id" => id, "relation" => relation_params}) do
    relation = Relations.get_relation!(id)

    case Relations.update_relation(relation, relation_params) do
      {:ok, relation} ->
        conn
        |> put_flash(:info, "Relation updated successfully.")
        |> redirect(to: Routes.relation_path(conn, :show, relation))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", relation: relation, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    relation = Relations.get_relation!(id)
    {:ok, _relation} = Relations.delete_relation(relation)

    conn
    |> put_flash(:info, "Relation deleted successfully.")
    |> redirect(to: Routes.relation_path(conn, :index))
  end

  def add(conn,_) do
    relation = %{sourceID: conn.params["id"],destinationID: conn.params["destinationID"],status: false}
    case Relations.check_rel(relation) and relation.sourceID != relation.destinationID do
      true -> rel_success(conn,relation)
      false ->  json(conn, %{message: "Oops,your friend request have been already submited or accepted!"})
    end
  end

  defp rel_success(conn,relation) do
    message =
      Relations.check_duplicate(relation)
    json(conn, %{message: message})
  end

  def incoming(conn, _) do
    inc =
      conn.params["id"]
      |>Relations.get_incoming_users()
    render(conn, "incoming.json", relation: inc)
  end

  def accept(conn, _) do
    Relations.accept_user(conn.params["id"], conn.params["destinationID"])
    json(conn, %{message: "Success!"})
  end
end

phoenixclient/lib/phoenixclient_web/views/relation_view.ex
defmodule PhoenixclientWeb.RelationView do
  use PhoenixclientWeb, :view
  alias PhoenixclientWeb.RelationView

  def render("index.json", %{relation: relation}) do
    %{data: render_many(relation, RelationView, "relation.json")}
  end
  def render("incoming.json", %{relation: relation}) do
    %{data: render_many(relation, RelationView, "user.json")}
  end

  def render("show.json", %{relation: relation}) do
    %{data: render_one(relation, RelationView, "relation.json")}
  end

  def render("relation.json", %{relation: relation}) do
    %{sourceID: relation.sourceID,
      destinationID: relation.destinationID,
      status: relation.status}
  end
  def render("user.json", %{relation: relation}) do
    %{id: relation.id,
      email: relation.email,
      name: relation.name}
  end
end

phoenixclient/lib/phoenixclient_web/templates/relation/edit.html.eex
<h1>Edit Relation</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.relation_path(@conn, :update, @relation)) %>

<span><%= link "Back", to: Routes.relation_path(@conn, :index) %></span>

phoenixclient/lib/phoenixclient_web/templates/relation/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :sourceID %>
  <%= number_input f, :sourceID %>
  <%= error_tag f, :sourceID %>

  <%= label f, :destinationID %>
  <%= number_input f, :destinationID %>
  <%= error_tag f, :destinationID %>

  <%= label f, :status %>
  <%= checkbox f, :status %>
  <%= error_tag f, :status %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

phoenixclient/lib/phoenixclient_web/templates/relation/incoming.html.eex
<h1>Incoming Users</h1>

<thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
</thead>

<table>
  <tbody>
    <%= for user <- @users do %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>

        <td>
          <%= link "Show", to: Routes.user_path(@conn, :show, user) %>
          <%= link "Edit", to: Routes.user_path(@conn, :edit, user) %>
          <%= link "Delete", to: Routes.user_path(@conn, :delete, user),
            method: :delete, data: [confirm: "Are you sure?"] %>
          <%= form_for @conn, Routes.relation_path(@conn, :accept), fn f -> %>

            <%= hidden_input f, :destinationID, value: user.id %>
            <%= submit "Accept" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

phoenixclient/lib/phoenixclient_web/templates/relation/index.html.eex
<h1>Listing Relation</h1>

<table>
  <thead>
    <tr>
      <th>Sourceid</th>
      <th>Destinationid</th>
      <th>Status</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for relation <- @relation do %>
    <tr>
      <td><%= relation.sourceID %></td>
      <td><%= relation.destinationID %></td>
      <td><%= relation.status %></td>

      <td>
        <span><%= link "Show", to: Routes.relation_path(@conn, :show, relation) %></span>
        <span><%= link "Edit", to: Routes.relation_path(@conn, :edit, relation) %></span>
        <span><%= link "Delete", to: Routes.relation_path(@conn, :delete, relation), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Relation", to: Routes.relation_path(@conn, :new) %></span>

phoenixclient/lib/phoenixclient_web/templates/relation/new.html.eex
<h1>New Relation</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.relation_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.relation_path(@conn, :index) %></span>

phoenixclient/lib/phoenixclient_web/templates/relation/show.html.eex
<h1>Show Relation</h1>

<ul>

  <li>
    <strong>Sourceid:</strong>
    <%= @relation.sourceID %>
  </li>

  <li>
    <strong>Destinationid:</strong>
    <%= @relation.destinationID %>
  </li>

  <li>
    <strong>Status:</strong>
    <%= @relation.status %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.relation_path(@conn, :edit, @relation) %></span>
<span><%= link "Back", to: Routes.relation_path(@conn, :index) %></span>