phoenixclient/lib/phoenixclient_web/router.ex
defmodule PhoenixclientWeb.Router do
  use PhoenixclientWeb, :router
  alias Routes

  pipeline :auth do #ログイン認証のためのパイプライン
    plug Phoenixclient.Accounts.Pipeline
  end

  pipeline :ensure_auth do  #ログイン済みであるかの判断のためのパイプライン
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json","multipart"]
  end

'''
  scope "/", PhoenixclientWeb do
    pipe_through [:browser, :api, :auth]

    post "/login", LoginController, :login #loginのための情報送信
    post "/add", RelationController, :add #フレンド申請
    delete "/logout", LoginController, :delete
    get "/", PageController, :index

    get "/login", LoginController, :index   #login画面を表示
  end
'''

  scope "/", PhoenixclientWeb do
    pipe_through :api
    get "/", PageController, :index

    get "/search", SearchController, :search#検索
    get "/locsearch", SearchController, :locsearch#検索

    resources "/users", UserController #usersパスへのすべてのリクエストを許可
    get "/userdata", UserController, :get_user # ユーザーのデータ取得

    resources "/locations", LocationController#位置登録

    post "/auth", LoginController, :auth # トークン認証のためのリクエスト
    post "/login", LoginController, :login # loginのための情報送信
    post "/logout", LoginController, :logout
    post "/refresh_token", LoginController, :refresh_token #アクセストークン再発行のルーティング

    post "/relations", RelationController, :add #フレンド追加
    get "/relations", RelationController, :index
    post "/accept", RelationController, :accept
    get "/incoming", RelationController, :incoming
    post "/image", ImageController, :upload# 画像アップロード
  end

  # scope "/", PhoenixclientWeb do
  # pipe_through [:browser, :auth, :ensure_auth]


  # Other scopes may use custom stacks.
  # scope "/api", PhoenixclientWeb do
  #   pipe_through :api
  # end
end

phoenixclient/lib/phoenixclient_web/views/layout_view.ex
defmodule PhoenixclientWeb.LayoutView do
  use PhoenixclientWeb, :view
  alias Phoenixclient.Accounts.Guardian
  def current_user(conn) do
    Guardian.Plug.current_resource(conn)
  end
end

phoenixclient/lib/phoenixclient_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Phoenixclient · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if current_user(@conn) do %>
+              <li><%= link "Logout", to: Routes.login_path(@conn, :delete), method: :delete %></li>
+            <% end %>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>